from django.utils import timezone
from rest_framework.authentication import BaseAuthentication, get_authorization_header
from rest_framework.exceptions import AuthenticationFailed
from oidc_provider.models import Token

class OIDCBearerAuthentication(BaseAuthentication):
    """
    Authenticate requests using Access Tokens generated by django-oidc-provider.
    Format: Authorization: Bearer <access_token>
    """
    keyword = 'Bearer'

    def authenticate(self, request):
        auth_header = get_authorization_header(request).split()

        if not auth_header:
            return None

        if auth_header[0].decode('utf-8').lower() != self.keyword.lower():
            return None

        if len(auth_header) == 1:
            raise AuthenticationFailed('Invalid token header. No credentials provided.')
        elif len(auth_header) > 2:
            raise AuthenticationFailed('Invalid token header. Token string should not contain spaces.')

        try:
            token_str = auth_header[1].decode('utf-8')
        except UnicodeError:
            raise AuthenticationFailed('Invalid token header. Token string contains invalid characters.')

        token = Token.objects.filter(access_token=token_str).select_related('user').first()
        if not token:
            raise AuthenticationFailed('Invalid access token.')

        if token.expires_at and token.expires_at < timezone.now():
            raise AuthenticationFailed('Access token has expired.')

        if not token.user.is_active:
            raise AuthenticationFailed('User account is inactive or disabled.')

        return (token.user, token)

    def authenticate_header(self, request):
        return self.keyword
