# Generated by Django 5.2.17 on 2026-10-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesplit',
            name='paid_marked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensesplit',
            name='pending_verification',
            field=models.BooleanField(default=False),
        ),
    ]
